### ISSUE TITLE
Feature: add list of all present members

### ISSUE THREAD

**Issue by ILoveAndLikePizza** [djoamersfoort/corvee#6]
De vernieuwde lichtkrant-module voor het corvee vereist dat de Corvee API een array van *aanwezige* mensen geeft naast *geselecteerde* mensen. De module zou het er bijvoorbeeld zo graag van willen hebben:
`{"present":["Nathan","Sverre","Kevin","Christof","Yannick","Fabe"]}, "selected":["Kevin","Christof","Yannick"]}`

Het belooft een prachtige nieuwe module te worden, hoop dat we dat kunnen regelen!

**Comment by rmoesbergen** [comment]
Fixed
